#pragma once

// FIX D Link 3 (docs/design-qwen-flash-next.md "Links 2 and 3"): the
// (token_history) -> row_index function for Qwen Flash Next's PLE n-gram
// embedding table, plus the dummy-weight derivation of its hash constants.
//
// This is the piece the previous session deferred as a "structural spec hole".
// The hole is closed by the code-side ground truth in docs/research-freetoken.md
// ("Code-side ground truth"), transcribed from the FreeToken reference
// implementation (Apache-2.0, pinned commit 505477ab,
// python/freetoken/models/qwen4_exp/ple.py): the table is NOT "one row per
// token id" -- it is a hashed-vocab lookup addressed by a GLOBAL hashed id.
//
// For each output token and each n-gram order n in [2, ngram_size], the last n
// token ids (with eos substituted wherever the window would cross a sequence
// boundary) are mixed by an XOR of per-position (token * multiplier) products,
// reduced modulo a per-head prime vocab size, and offset into a concatenated
// global row space. `heads_per_ngram` heads share each order's mixed value and
// differ only by their vocab size and offset; there are
// `(ngram_size-1) * heads_per_ngram` heads in total (16 on Qwen3.8: 8 x 2-gram
// + 8 x 3-gram). Each head gathers one 160-wide row, so a token yields
// `num_ngram_heads` rows -> `num_ngram_heads * 160` embedding elements.
//
// The three int64 buffers (layer_multipliers, ngram_heads_vocab_sizes,
// ngram_heads_offsets) ship as trained checkpoint tensors. Until a Flash-Next
// artifact exists, `derive_hash_constants` below reproduces the reference's own
// DUMMY-weight derivation ("the way HF derives them at init",
// ple.py::derive_ngram_hash_constants) -- the same values the reference uses
// as the oracle for a loaded checkpoint. `tests/test_ngram_row_ids.cpp` checks
// both `derive_hash_constants` and `row_ids` byte-for-byte against vectors the
// reference itself produced (tests/ngram_row_ids_vectors.h, generated by
// tools/gen_ngram_vectors.py). A check of arcint's loaded buffers against the
// real checkpoint tensors is still owed once an artifact exists.
//
// Pure integer arithmetic, no torch, no device, no IO -- unit-testable in the
// local (non-OpenVINO) build.

#include <algorithm>
#include <cstdint>
#include <limits>
#include <stdexcept>
#include <string>
#include <vector>

#include "util/log.h"

namespace lgc::ngram {

// The per-layer hash constants + geometry for one PLE layer. `row_ids` needs
// exactly these; nothing about the table bytes or the device.
struct HashParams {
    int     ngram_size      = 0;
    int     heads_per_ngram = 0;
    int64_t eos_token_id    = 0;
    std::vector<int64_t> layer_multipliers;        // [ngram_size]
    std::vector<int64_t> ngram_heads_vocab_sizes;  // [num_ngram_heads]
    std::vector<int64_t> ngram_heads_offsets;      // [num_ngram_heads]

    int num_ngram_heads() const { return (ngram_size - 1) * heads_per_ngram; }

    // Throws with a named reason if the shapes are internally inconsistent, a
    // vocab size is non-positive (a modulo-by-zero or negative-divisor waiting
    // to happen), or ngram_size < 2 (no n-gram order to mix).
    void validate() const {
        if (ngram_size < 2)
            throw std::runtime_error(
                log::format("ngram row_ids: ngram_size %d < 2", ngram_size));
        if (heads_per_ngram < 1)
            throw std::runtime_error(
                log::format("ngram row_ids: heads_per_ngram %d < 1", heads_per_ngram));
        if (static_cast<int>(layer_multipliers.size()) != ngram_size)
            throw std::runtime_error(log::format(
                "ngram row_ids: layer_multipliers has %zu entries, ngram_size is %d",
                layer_multipliers.size(), ngram_size));
        const int H = num_ngram_heads();
        if (static_cast<int>(ngram_heads_vocab_sizes.size()) != H ||
            static_cast<int>(ngram_heads_offsets.size()) != H)
            throw std::runtime_error(log::format(
                "ngram row_ids: head buffers are %zu/%zu long, expected %d "
                "((ngram_size-1)*heads_per_ngram)",
                ngram_heads_vocab_sizes.size(), ngram_heads_offsets.size(), H));
        if (eos_token_id < 0)
            throw std::runtime_error(log::format(
                "ngram row_ids: eos_token_id %lld is negative (no hash boundary set)",
                static_cast<long long>(eos_token_id)));
        int64_t prev_offset = -1;
        for (int h = 0; h < H; ++h) {
            if (ngram_heads_vocab_sizes[h] <= 0)
                throw std::runtime_error(log::format(
                    "ngram row_ids: head %d vocab size %lld is not positive", h,
                    static_cast<long long>(ngram_heads_vocab_sizes[h])));
            if (ngram_heads_offsets[h] <= prev_offset)
                throw std::runtime_error(log::format(
                    "ngram row_ids: head %d offset %lld is not strictly increasing "
                    "(concatenated global row space must not overlap)",
                    h, static_cast<long long>(ngram_heads_offsets[h])));
            prev_offset = ngram_heads_offsets[h];
        }
    }
};

// Global table row per (token, hash head): row-major [tokens.size() *
// num_ngram_heads]. `context` is the `ngram_size - 1` token ids immediately
// before `tokens[0]` (all `eos_token_id` for a fresh sequence). This is one
// request's worth; the caller concatenates requests (each with its own
// context) the way the paged loop batches them.
//
// Byte-for-byte transcription of ple.py NGramEmbedding.row_ids +
// _shift_ignore_eos for num_reqs == 1 (see the file header). The int64 wrap and
// floor-mod match torch's int64 multiply / bitwise_xor / remainder exactly:
// products are formed in uint64 (two's-complement wrap == torch int64 wrap),
// XORed as bit patterns, then reduced with a floor modulo. Under the
// reference's own `half_bound` bound every `token * multiplier` is strictly
// below 2^63, so `mixed` is provably non-negative and the negative-branch of
// the floor-mod is never taken; it is kept as a correctness guard, not a live
// path (see tools/gen_ngram_vectors.py).
inline std::vector<int64_t> row_ids(const HashParams&           p,
                                    const std::vector<int64_t>& context,
                                    const std::vector<int64_t>& tokens) {
    p.validate();
    const int ctx_len = p.ngram_size - 1;
    if (static_cast<int>(context.size()) != ctx_len)
        throw std::runtime_error(log::format(
            "ngram row_ids: context has %zu ids, ngram_size-1 is %d",
            context.size(), ctx_len));

    // packed = context ++ tokens; the hash window for token i sits at column
    // ctx_len + i and reaches ngram_size-1 columns to its left.
    std::vector<int64_t> packed;
    packed.reserve(context.size() + tokens.size());
    packed.insert(packed.end(), context.begin(), context.end());
    packed.insert(packed.end(), tokens.begin(), tokens.end());
    const size_t W = packed.size();

    // in_segment[pos] = number of non-boundary columns strictly before `pos`
    // since the last eos (ple.py _shift_ignore_eos: pos - prev_eos - 1, with
    // prev_eos the last eos index strictly before pos, or -1). A shift `s` at
    // column `pos` is valid only when in_segment[pos] >= s, so no n-gram ever
    // crosses an eos.
    std::vector<int64_t> in_segment(W);
    int64_t              last_eos = -1;
    for (size_t pos = 0; pos < W; ++pos) {
        in_segment[pos] = static_cast<int64_t>(pos) - last_eos - 1;
        if (packed[pos] == p.eos_token_id) last_eos = static_cast<int64_t>(pos);
    }

    // The token `s` columns left of `col`, or eos when the window runs off the
    // start or crosses a boundary. Shift 0 is always packed[col] itself.
    auto shifted_token = [&](size_t col, int s) -> int64_t {
        const long src = static_cast<long>(col) - s;
        if (src >= 0 && in_segment[col] >= s) return packed[static_cast<size_t>(src)];
        return p.eos_token_id;
    };

    const int    H = p.num_ngram_heads();
    const size_t T = tokens.size();
    std::vector<int64_t> out(T * static_cast<size_t>(H));
    for (size_t i = 0; i < T; ++i) {
        const size_t col = context.size() + i;
        for (int ngram = 2; ngram <= p.ngram_size; ++ngram) {
            const int start = (ngram - 2) * p.heads_per_ngram;
            uint64_t  mixed = static_cast<uint64_t>(shifted_token(col, 0)) *
                             static_cast<uint64_t>(p.layer_multipliers[0]);
            for (int position = 1; position < ngram; ++position) {
                mixed ^= static_cast<uint64_t>(shifted_token(col, position)) *
                         static_cast<uint64_t>(p.layer_multipliers[position]);
            }
            const int64_t sm = static_cast<int64_t>(mixed);  // torch int64 reinterpret
            for (int h = start; h < start + p.heads_per_ngram; ++h) {
                const int64_t v = p.ngram_heads_vocab_sizes[h];
                int64_t       r = sm % v;
                if (r < 0) r += v;  // floor modulo; unreachable under the half_bound bound
                out[i * static_cast<size_t>(H) + h] = r + p.ngram_heads_offsets[h];
            }
        }
    }
    return out;
}

namespace detail {

inline constexpr uint64_t kSplitmixGamma = 0x9E3779B97F4A7C15ULL;
inline constexpr uint64_t kSplitmixM1    = 0xBF58476D1CE4E5B9ULL;
inline constexpr uint64_t kSplitmixM2    = 0x94D049BB133111EBULL;
inline constexpr int      kPleLayerPrime = 10007;

// splitmix64, matching ple.py::_splitmix64. uint64 arithmetic is mod 2^64, so
// the reference's explicit `& _MASK64` masks are implicit here.
inline uint64_t splitmix64(uint64_t value) {
    value = value + kSplitmixGamma;
    value = (value ^ (value >> 30)) * kSplitmixM1;
    value = (value ^ (value >> 27)) * kSplitmixM2;
    return value ^ (value >> 31);
}

inline bool is_prime(int64_t value) {
    if (value < 2) return false;
    if (value % 2 == 0) return value == 2;
    for (int64_t divisor = 3; divisor * divisor <= value; divisor += 2) {
        if (value % divisor == 0) return false;
    }
    return true;
}

inline int64_t nth_prime_after(int64_t start, int64_t count) {
    int64_t prime = start;
    for (int64_t k = 0; k < count; ++k) {
        prime += 1;
        while (!is_prime(prime)) prime += 1;
    }
    return prime;
}

}  // namespace detail

// The reference's dummy-weight constant derivation
// (ple.py::derive_ngram_hash_constants) ported to C++. The checkpoint ships
// these as int64 tensors; this reproduces "the way HF derives them at init" and
// is the oracle a loaded checkpoint is checked against. `seed` defaults to the
// reference's own 1234.
inline HashParams derive_hash_constants(int64_t vocab_size, int ngram_size,
                                        int heads_per_ngram, int64_t ngram_vocab_size_base,
                                        int ple_layer_index, int64_t seed = 1234) {
    HashParams p;
    p.ngram_size      = ngram_size;
    p.heads_per_ngram = heads_per_ngram;
    const int num_heads = (ngram_size - 1) * heads_per_ngram;

    // ((1<<63)-1) in the reference (Python big-int) is INT64_MAX here; forming
    // it as a shift into the sign bit would be signed overflow (UB).
    const int64_t half_bound = std::max<int64_t>(
        1, std::numeric_limits<int64_t>::max() / std::max<int64_t>(vocab_size, 1) / 2);
    const uint64_t base_seed =
        static_cast<uint64_t>(seed) +
        static_cast<uint64_t>(detail::kPleLayerPrime) * static_cast<uint64_t>(ple_layer_index);

    p.layer_multipliers.resize(ngram_size);
    for (int i = 0; i < ngram_size; ++i) {
        const uint64_t mixed =
            detail::splitmix64(base_seed + detail::kSplitmixGamma * static_cast<uint64_t>(i + 1));
        p.layer_multipliers[i] =
            2 * static_cast<int64_t>(mixed % static_cast<uint64_t>(half_bound)) + 1;
    }

    p.ngram_heads_vocab_sizes.resize(num_heads);
    p.ngram_heads_offsets.resize(num_heads);
    int64_t total = 0;
    for (int head = 0; head < num_heads; ++head) {
        const int64_t global_head =
            static_cast<int64_t>(ple_layer_index) * num_heads + head;
        const int64_t size = detail::nth_prime_after(ngram_vocab_size_base - 1, global_head + 1);
        p.ngram_heads_vocab_sizes[head] = size;
        p.ngram_heads_offsets[head]     = total;
        total += size;
    }
    return p;
}

// The minimum physical row count a per_layer_token_embd table must have to hold
// every row id `row_ids` can produce, under the corrected hashed-vocab spec.
//
// This supersedes the pre-correction admission formula
// (`ngram_vocab_size_base * (ple_embed_dim / 160)`), which assumed a plain
// "N physical rows per vocab entry" table and is demonstrably inconsistent with
// the reference: the physical table is sized to `offsets[-1] + sizes[-1]`
// (ple.py::derive_ngram_hash_constants -> model.py:164 ZeroTable /
// weight.py:303 HostBank), i.e. the concatenated per-head prime vocab sizes,
// which exceed `base * num_heads` (every prime is >= base) and grow with the
// PLE layer index (global_head = ple_layer_index * num_heads + head). A shared
// PinnedUVATable spans every PLE layer, so the last layer's band is the highest
// row any lookup can reach; that band's top is the required minimum.
//
// This is a strict LOWER bound, not an equality: it is provably necessary (a
// lookup can reach `return value - 1`) but does not pin the exact shipped size,
// which the checkpoint may pad up via `split_ngram_parts` -- an equality would
// need a real artifact to verify (see docs/design-qwen-flash-next.md FIX D
// "Links 2 and 3", reconcile flag).
inline int64_t ngram_required_rows(int64_t vocab_size, int ngram_size, int heads_per_ngram,
                                   int64_t ngram_vocab_size_base, int num_ple_layers) {
    const int last = std::max(0, num_ple_layers - 1);
    const HashParams p = derive_hash_constants(vocab_size, ngram_size, heads_per_ngram,
                                               ngram_vocab_size_base, last);
    return p.ngram_heads_offsets.back() + p.ngram_heads_vocab_sizes.back();
}

}  // namespace lgc::ngram
