// GENERATED by tools/gen_ngram_vectors.py -- DO NOT EDIT BY HAND.
//
// FIX D Link 3 (docs/design-qwen-flash-next.md): ground-truth row_ids()
// vectors for tests/test_ngram_row_ids.cpp. The per-head hash constants
// (multipliers / vocab sizes / offsets) are produced by the FreeToken
// reference's own derive_ngram_hash_constants (Apache-2.0, pinned commit
// 505477ab4429579e552adedd165f3cd6dbd40200); the expected row ids are the
// documented XOR-multiply mixing transcribed in the generator. Neither
// is copied from the reference test suite (see the generator's header).
//
// Regenerate: python3 tools/gen_ngram_vectors.py   (needs the pinned
// reference checkout; --check diffs without writing).
#pragma once
#include <cstdint>
#include <vector>

namespace lgc::ngram::test_vectors {

struct RowIdsVector {
    const char*          name;
    int                  ngram_size;
    int                  heads_per_ngram;
    int64_t              eos_token_id;
    std::vector<int64_t> layer_multipliers;       // [ngram_size]
    std::vector<int64_t> ngram_heads_vocab_sizes;  // [num_ngram_heads]
    std::vector<int64_t> ngram_heads_offsets;      // [num_ngram_heads]
    std::vector<int64_t> context;                  // [ngram_size-1]
    std::vector<int64_t> tokens;                   // [T]
    int64_t              total_rows;               // global row-space size
    std::vector<int64_t> expected_row_ids;         // row-major [T * num_ngram_heads]
};

inline std::vector<RowIdsVector> row_ids_vectors() {
    return {
        RowIdsVector{
            "basic_2gram_only",
            2, 3, 0,
            {32798821421693457, 24769768445502803},
            {29, 31, 37},
            {0, 29, 60},
            {5},
            {11, 12, 13, 14},
            97,
            {3, 57, 84, 24, 51, 63, 9, 43, 88, 19, 36, 61},
        },
        RowIdsVector{
            "trigram_no_eos",
            3, 2, 0,
            {32798821421693457, 24769768445502803, 11235615054459833},
            {31, 37, 41, 43},
            {0, 31, 68, 109},
            {7, 9},
            {21, 22, 23, 24, 25},
            152,
            {22, 37, 75, 113, 28, 34, 70, 120, 30, 66, 105, 129, 25, 61, 79, 121, 21, 61, 83, 128},
        },
        RowIdsVector{
            "trigram_eos_midseq",
            3, 2, 0,
            {17439310383707687, 20377756208257461, 14788019763345549},
            {47, 53, 59, 61},
            {0, 47, 100, 159},
            {3, 4},
            {31, 0, 33, 34},
            220,
            {39, 71, 125, 204, 8, 47, 151, 197, 12, 93, 145, 191, 37, 51, 119, 212},
        },
        RowIdsVector{
            "trigram_fresh_context",
            3, 2, 0,
            {17613196698328715, 28445123073762771, 27276139156055515},
            {17, 19, 23, 29},
            {0, 17, 36, 59},
            {0, 0},
            {41, 42, 43},
            88,
            {4, 31, 53, 83, 13, 20, 57, 62, 8, 29, 36, 75},
        },
        RowIdsVector{
            "decode_single_token",
            3, 4, 0,
            {32798821421693457, 24769768445502803, 11235615054459833},
            {47, 53, 59, 61, 67, 71, 73, 79},
            {0, 47, 100, 159, 220, 287, 358, 431},
            {51, 52},
            {53},
            510,
            {24, 96, 120, 171, 272, 321, 385, 502},
        },
        RowIdsVector{
            "qwen_scale_16head",
            3, 8, 151643,
            {55689588136953, 470142627999, 8456664255937},
            {8647, 8663, 8669, 8677, 8681, 8689, 8693, 8699, 8707, 8713, 8719, 8731, 8737, 8741, 8747, 8753},
            {0, 8647, 17310, 25979, 34656, 43337, 52026, 60719, 69418, 78125, 86838, 95557, 104288, 113025, 121766, 130513},
            {151935, 151934},
            {151935, 100000, 1},
            139266,
            {4104, 10451, 20632, 28567, 35758, 48822, 59668, 60951, 69831, 78877, 90110, 100964, 110828, 117668, 127976, 133877, 6497, 17039, 17761, 26319, 40248, 47145, 59733, 68374, 77072, 80712, 87112, 96574, 108215, 113432, 122627, 137266, 1084, 13802, 23133, 29380, 34885, 45252, 58276, 61337, 77181, 83035, 91613, 96487, 109598, 121711, 122064, 137761},
        },
    };
}

}  // namespace lgc::ngram::test_vectors
