// nvme-direct-expert-tier (0.5.3 LISBON), D2/D3 -- the load-time pinned fill's
// schedule, tested device-free against a fake transport. No card, no arcwell
// module, no expert store: these cells pin the CONTRACT the design note fixes
// (`docs/design-nvme-direct-expert-tier.md` §3/§4), so a wiring mistake cannot
// reach a card window.
//
// Red-first. The ladder is green here; the mutation evidence is generated by
// rebuilding this file against mutant copies of `src/exec/pinned_nvme_fill.h`
// (guard removed, refusal replaced by a silent fill, depth ignored). Each
// mutant is recorded in the campaign's own evidence packet, not in this tree.

#include "harness.h"

#include <cstdint>
#include <filesystem>
#include <fstream>
#include <functional>
#include <map>
#include <sstream>
#include <string>
#include <vector>

#include "exec/pinned_nvme_fill.h"

namespace {

using lgc::nvme_fill::CollectOutcome;
using lgc::nvme_fill::FillBatch;
using lgc::nvme_fill::FillRequest;
using lgc::nvme_fill::Phase;
using lgc::nvme_fill::Scheduler;
using lgc::nvme_fill::Transport;

// A fake arcwell batch transport. `complete` returns how many of a batch's
// requests land on the given attempt (1-based); a value smaller than the batch
// size models a short transfer. It also records the largest number of batches
// that were simultaneously submitted-but-not-collected, which is the in-flight
// depth the schedule is supposed to hold at four.
struct FakeTransport : Transport {
    struct Submission {
        std::uint64_t id = 0;
        FillBatch     batch;
        int           attempt = 1;
    };

    std::vector<Submission>        submissions;
    std::map<std::uint64_t, FillBatch> inflight;
    std::map<std::uint32_t, int>   attempts;  // per layer
    std::size_t                    max_inflight = 0;
    std::uint64_t                  next_id = 1;

    bool begin_ok = true;
    std::string begin_reason;
    std::function<std::size_t(const FillBatch&, int)> complete =
        [](const FillBatch& b, int) { return b.requests.size(); };

    bool begin(std::string* reason) override {
        if (!begin_ok) {
            if (reason) *reason = begin_reason;
            return false;
        }
        return true;
    }

    bool submit(const FillBatch& batch, std::uint64_t* batch_id, std::string*) override {
        Submission s;
        s.id      = next_id++;
        s.batch   = batch;
        s.attempt = ++attempts[batch.layer];
        submissions.push_back(s);
        inflight.emplace(s.id, batch);
        if (inflight.size() > max_inflight) max_inflight = inflight.size();
        *batch_id = s.id;
        return true;
    }

    bool collect(std::uint64_t batch_id, CollectOutcome* outcome, std::string*) override {
        auto it = inflight.find(batch_id);
        if (it == inflight.end()) return false;
        const FillBatch batch = it->second;
        inflight.erase(it);
        const int attempt = attempts[batch.layer];
        outcome->requested = batch.requests.size();
        outcome->completed = complete(batch, attempt);
        outcome->ok        = (outcome->completed == batch.requests.size());
        return true;
    }
};

FillBatch make_batch(std::uint32_t layer, std::size_t n) {
    FillBatch b;
    b.layer = layer;
    for (std::size_t i = 0; i < n; ++i) {
        FillRequest r;
        r.layer  = layer;
        r.expert = static_cast<std::uint32_t>(i);
        r.slot   = static_cast<std::uint32_t>(i);
        r.lba    = 1000 + layer * 100 + i;
        r.bytes  = 2457600;
        b.requests.push_back(r);
    }
    return b;
}

}  // namespace

// The schedule is one batch per layer: six layers enqueue six batches, each
// holding that layer's pinned set, and every request is marked filled exactly
// once -- on collect, not on submit.
TEST(pinned_nvme_fill_one_batch_per_layer) {
    FakeTransport t;
    Scheduler     s(&t, 4);
    std::string   why;
    CHECK(s.begin(&why));

    for (std::uint32_t layer = 0; layer < 6; ++layer) CHECK(s.enqueue(make_batch(layer, 3), &why));

    std::vector<std::uint32_t> filled_layers;
    CHECK(s.barrier([&](const FillRequest& r) { filled_layers.push_back(r.layer); }, &why));

    CHECK_EQ(t.submissions.size(), std::size_t{6});
    for (std::size_t i = 0; i < t.submissions.size(); ++i) {
        CHECK_EQ(t.submissions[i].batch.layer, static_cast<std::uint32_t>(i));
        CHECK_EQ(t.submissions[i].batch.requests.size(), std::size_t{3});
    }
    CHECK_EQ(filled_layers.size(), std::size_t{18});
    CHECK(s.phase() == Phase::kServing);
}

// Four batches in flight: the scheduler fills the window before it collects
// the oldest, so the NVMe queue depth is used (the note's measured shape).
TEST(pinned_nvme_fill_holds_four_batches_in_flight) {
    FakeTransport t;
    Scheduler     s(&t, 4);
    std::string   why;
    CHECK(s.begin(&why));
    for (std::uint32_t layer = 0; layer < 10; ++layer) CHECK(s.enqueue(make_batch(layer, 2), &why));

    CHECK(s.barrier([](const FillRequest&) {}, &why));
    CHECK_EQ(t.max_inflight, std::size_t{4});
    CHECK_EQ(t.submissions.size(), std::size_t{10});
    CHECK(t.inflight.empty());
}

// A short batch is retried once, in full; if the retry lands, the load
// succeeds and the retried experts are marked filled. The retried batch is the
// whole layer, because partial completion does not name which request landed.
TEST(pinned_nvme_fill_short_batch_is_retried_then_lands) {
    FakeTransport t;
    // Layer 4 is short on its first attempt, complete on its second.
    t.complete = [](const FillBatch& b, int attempt) -> std::size_t {
        if (b.layer == 4 && attempt == 1) return b.requests.size() - 1;
        return b.requests.size();
    };
    Scheduler   s(&t, 4);
    std::string why;
    CHECK(s.begin(&why));
    for (std::uint32_t layer = 0; layer < 6; ++layer) CHECK(s.enqueue(make_batch(layer, 3), &why));

    std::map<std::uint32_t, std::size_t> filled_per_layer;
    CHECK(s.barrier([&](const FillRequest& r) { ++filled_per_layer[r.layer]; }, &why));
    CHECK_EQ(filled_per_layer[4], std::size_t{3});
    CHECK_EQ(t.attempts[4], 2);
    CHECK_EQ(t.submissions.size(), std::size_t{7});  // six once, layer 4 twice
    CHECK(s.phase() == Phase::kServing);
}

// A pinned expert that is still not landed after its retry is a LOAD FAILURE:
// the barrier refuses, and no request from that layer is ever marked filled.
// It is never silently demoted to the host tier.
TEST(pinned_nvme_fill_refuses_a_pinned_expert_that_never_lands) {
    FakeTransport t;
    t.complete = [](const FillBatch& b, int) -> std::size_t {
        if (b.layer == 3) return 0;  // never lands, on any attempt
        return b.requests.size();
    };
    Scheduler   s(&t, 4);
    std::string why;
    CHECK(s.begin(&why));
    for (std::uint32_t layer = 0; layer < 5; ++layer) CHECK(s.enqueue(make_batch(layer, 2), &why));

    std::vector<std::uint32_t> filled_layers;
    CHECK(!s.barrier([&](const FillRequest& r) { filled_layers.push_back(r.layer); }, &why));
    for (std::uint32_t layer : filled_layers) CHECK(layer != 3u);
    CHECK(why.find("refusing the load") != std::string::npos);
    CHECK(why.find("layer 3") != std::string::npos);
    CHECK(s.phase() == Phase::kRefused);  // terminal, never advanced to serving
    CHECK_EQ(t.attempts[3], 2);           // exactly one retry

    // A refusal is terminal: a second barrier must not resume into serving.
    CHECK(!s.barrier([&](const FillRequest& r) { filled_layers.push_back(r.layer); }, &why));
    CHECK(s.phase() == Phase::kRefused);
    CHECK(why.find("already refused") != std::string::npos);
}

// Whole-configuration setup failure: if arcwell cannot be set up at all (the
// MAP_BUFFER contract, the BO, the batch surface), that is a load failure too.
TEST(pinned_nvme_fill_setup_failure_is_a_load_failure) {
    FakeTransport t;
    t.begin_ok     = false;
    t.begin_reason = "AW_IOC_MAP_BUFFER refused: no peer-to-peer mapping";
    Scheduler   s(&t, 4);
    std::string why;
    CHECK(!s.begin(&why));
    CHECK_EQ(why, std::string("AW_IOC_MAP_BUFFER refused: no peer-to-peer mapping"));
    CHECK(s.phase() == Phase::kCreated);
}

// The campaign's Out, made unreachable: a synchronous AW_IOC_READ_BLOCKS is
// refused by this code once the load barrier has passed. This is the red-first
// cell the campaign names -- removing the guard in require_no_sync_read makes
// it fail.
TEST(pinned_nvme_fill_refuses_a_synchronous_read_on_the_decode_path) {
    FakeTransport t;
    Scheduler     s(&t, 4);
    std::string   why;
    CHECK(s.begin(&why));
    CHECK(s.enqueue(make_batch(0, 1), &why));

    // During the load phase a synchronous path would be tolerated (there is
    // none wired, but the guard must not fire early).
    bool threw_at_load = false;
    try {
        s.require_no_sync_read("AW_IOC_READ_BLOCKS");
    } catch (const std::logic_error&) {
        threw_at_load = true;
    }
    CHECK(!threw_at_load);

    CHECK(s.barrier([](const FillRequest&) {}, &why));
    CHECK(s.phase() == Phase::kServing);

    bool threw_serving = false;
    try {
        s.require_no_sync_read("AW_IOC_READ_BLOCKS");
    } catch (const std::logic_error&) {
        threw_serving = true;
    }
    CHECK(threw_serving);
}

// Ordering guards: batches may only be enqueued during the load phase, and the
// barrier may not run twice.
TEST(pinned_nvme_fill_refuses_enqueue_outside_the_load_phase) {
    FakeTransport t;
    Scheduler     s(&t, 4);
    std::string   why;
    CHECK(s.begin(&why));
    CHECK(s.enqueue(make_batch(0, 1), &why));
    CHECK(s.barrier([](const FillRequest&) {}, &why));

    CHECK(!s.enqueue(make_batch(1, 1), &why));
    CHECK(!s.barrier([](const FillRequest&) {}, &why));
}

// Drift guard. The plugin patch (patches/0048-...) adds its own copy of the
// schedule as moe/pinned_nvme_fill.hpp, because the OpenVINO plugin build
// cannot see arcint's src/exec. The two must be byte-identical: the tracked
// header is the one the ladder above tests, and a silent divergence would make
// the tested schedule and the compiled one different programs. Every added line
// of the patch's new file is compared against the tracked header.
TEST(pinned_nvme_fill_plugin_copy_matches_the_tracked_header) {
    namespace fs = std::filesystem;
    const fs::path root   = std::string(ARCINT_SOURCE_DIR);
    const fs::path patch  = root / "patches/0048-moe-otd-pinned-nvme-fill.patch";
    const fs::path header = root / "src/exec/pinned_nvme_fill.h";
    CHECK(fs::exists(patch));
    CHECK(fs::exists(header));

    std::ifstream in(patch, std::ios::binary);
    std::stringstream buffer;
    buffer << in.rdbuf();
    const std::string text = buffer.str();

    const std::string marker = "+++ b/src/plugins/intel_gpu/src/graph/impls/ocl_v2/moe/pinned_nvme_fill.hpp";
    const std::size_t at = text.find(marker);
    CHECK(at != std::string::npos);

    // Collect the new file's added lines, up to the next `diff --git`.
    std::string extracted;
    std::size_t cursor = text.find('\n', at) + 1;
    while (cursor < text.size()) {
        const std::size_t eol = text.find('\n', cursor);
        const std::string line = text.substr(cursor, (eol == std::string::npos ? text.size() : eol) - cursor);
        if (line.rfind("diff --git ", 0) == 0) break;
        if (!line.empty() && line[0] == '+' && line.rfind("+++", 0) != 0)
            extracted += line.substr(1) + "\n";
        if (eol == std::string::npos) break;
        cursor = eol + 1;
    }

    std::ifstream h(header, std::ios::binary);
    std::stringstream hbuf;
    hbuf << h.rdbuf();
    CHECK_EQ(extracted, hbuf.str());
}
