"""THE FILL, accepted: real Q3_K_XL rows in the serving-shape IR's u4 expert
bodies.

198b736 emitted the 48-layer backbone at real geometry with every expert body
DECLARED and never materialised. That artifact proves the shape and carries no
weights, so nothing numeric could be asked of it. This file accepts the other
half: the bodies FILLED from the shipped checkpoint, byte-addressably, and what
comes back out of the pages equal to what the file holds.

THREE ACCEPTANCES, and each carries its own negative:

  (a) STRUCTURAL. Every expert body written exactly once. The census is
      GENERATED by the filler's own log -- bodies, layers, kinds, experts,
      bytes -- never written down here, and the arena's written-byte total is
      cross-checked against the byte count the declared shapes imply. Zero
      unwritten bodies and zero double-writes are the two failures a numeric
      leg could not see: a double-written body still dequantises to something
      plausible, and an unwritten one is a block of zeros no sampled expert
      need ever touch.

  (b) CONTENT. For sampled experts at TWO geometries -- gate/up at
      [512, 640, 20, 128] and down at [512, 2560, 5, 128], which differ in
      both the output width and the number of groups -- the filled body is
      read back OUT OF THE ARENA PAGES, unpacked by a transcription of the
      C++ (`src/core/gguf_repack.cpp:225`), dequantised by the IR's own chain
      arithmetic, and compared against `gguf_feed`'s f32 for the same row. The
      tolerance is the u4 representation's OWN rounding -- half a group step,
      `scale/2` -- and nothing is asserted below it. It is also asserted to be
      TIGHT, because a bound nothing approaches passes vacuously.

  (c) END TO END. One real-weights MoE layer piece, filled, executed on the
      CPU plugin and compared against the pin-fed reference. The comparison is
      SPLIT, and that is the point: against the dequantised-u4 weights the
      plumbing must be at the f32 floor, and against the raw f32 weights the
      difference is the quantisation cost, reported with the bound that
      predicts it. Blending the two would hide a packing bug inside a
      quantisation budget.

Real-weight source: the shipped UD-Q3_K_XL shards, same `Q4E_GGUF_SHARDS`
convention as test_gguf_feed.py -- absent, every cell here skips by name. The
u4-order and quantiser cells need neither shards nor a card and always run.

Run (dev host):
    Q4E_GGUF_SHARDS=<shard-dir> Q4E_GPU= <venv>/bin/python3 -m pytest \\
        tests/python/test_expert_fill.py -s
"""
import os
import sys
from pathlib import Path

import numpy as np
import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "tools"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import openvino as ov  # noqa: E402
from openvino import opset13 as opv  # noqa: E402

from q4e import expert_fill as ef  # noqa: E402
from q4e import gguf_feed  # noqa: E402
from q4e import piecewise_export as pwe  # noqa: E402
from q4e import serving_shape as ss  # noqa: E402

_SHARDS = os.environ.get("Q4E_GGUF_SHARDS", "").strip()
_skip = pytest.mark.skipif(
    not _SHARDS, reason="Q4E_GGUF_SHARDS unset (real GGUF shards absent)")

# How far past the u4 representation's own half-step a measured error may sit
# and still count as "at the representation's floor". This is NOT a fudge
# budget: the codes are chosen against the same f32 scale the graph multiplies
# by, so the bound holds in exact arithmetic, and what is left is the f32
# rounding of the reconstruction itself -- a few ulps on a value of order the
# scale. Measured at real width the worst ratio is 1.000001, i.e. 1e-6 over,
# which is where this number comes from.
_BOUND_SLACK = 1e-5

# The fill's structural acceptance runs at the REAL expert count over two
# layers. Two rather than one because one layer cannot tell a correct fill
# from one that feeds every layer block 0's weights.
_FILL_LAYERS = (0, 1)


# ---------------------------------------------------------------------------
# The packing contract -- device-free, no shards. Everything else rests here.
# ---------------------------------------------------------------------------

def test_openvino_u4_element_order_is_the_cpp_contract():
    """THE LOAD-BEARING FACT, and it had never been measured.

    arcint packs u4 "two per byte, even index low nibble"
    (`src/core/gguf_repack.h:90`), executed at `src/core/gguf_repack.cpp:225`:

        q = (r.weights[idx / 2] >> ((idx & 1) * 4)) & 0xF;

    Whether OPENVINO reads a u4 buffer the same way is a separate question,
    and the entire fill rests on the answer: the other convention swaps every
    adjacent pair of weights and yields a model that loads, runs, and is
    wrong -- with no error anywhere.

    Production already bets on it. `src/exec/gguf_graph.cpp:222-223` hands a
    `RepackedTensor::weights` buffer straight to an
    `ov::op::v0::Constant(ov::element::u4, ...)`. This cell is that bet,
    measured.
    """
    buf = np.array([0x21, 0x43], np.uint8)
    t = ov.Tensor(buf, ov.Shape([4]), ov.Type.u4)
    m = ov.Model([opv.result(opv.convert(opv.constant(t), ov.Type.f32))], [],
                 "u4_order")
    out = ov.Core().compile_model(m, "CPU")({})
    got = [int(v) for v in np.asarray(list(out.values())[0]).ravel()]
    cpp = [int(v) for v in ef.unpack_u4(buf, 4)]
    print(f"\n[u4-order] bytes 0x21 0x43 as u4[4]: OpenVINO {got}, "
          f"gguf_repack.cpp:225 {cpp}")
    assert cpp == [1, 2, 3, 4], (
        f"the C++ transcription itself is wrong: {cpp}, expected [1,2,3,4] "
        f"for even-index-low-nibble")
    assert got == cpp, (
        f"OPENVINO AND ARCINT DISAGREE ON u4 NIBBLE ORDER: OpenVINO reads "
        f"{got} where gguf_repack.cpp:225 reads {cpp}. Every adjacent pair of "
        f"expert weights would be swapped. This is not a test to relax -- "
        f"src/exec/gguf_graph.cpp:222 already hands repacked buffers straight "
        f"to an ov u4 Constant in production.")

    # and on a buffer big enough that an accidental agreement is not luck
    rng = np.random.default_rng(20260912)
    q = rng.integers(0, 16, size=4096, dtype=np.uint8)
    packed = ef.pack_u4(q)
    t2 = ov.Tensor(packed, ov.Shape([4096]), ov.Type.u4)
    m2 = ov.Model([opv.result(opv.convert(opv.constant(t2), ov.Type.f32))], [],
                  "u4_order_big")
    back = np.asarray(list(ov.Core().compile_model(m2, "CPU")({}).values())[0])
    back = back.astype(np.uint8).ravel()
    bad = int((back != q).sum())
    print(f"[u4-order] 4096 random codes through pack_u4 -> ov u4 Constant -> "
          f"Convert(f32): {bad} mismatches")
    assert bad == 0, f"{bad} of 4096 codes came back wrong"
    assert np.array_equal(ef.unpack_u4(packed, 4096), q), (
        "the C++ transcription does not invert pack_u4 on random codes")


def test_the_quantiser_holds_its_half_step_bound_and_the_bound_is_tight():
    """The rounding this representation is entitled to, asserted both ways.

    `|v - v_hat| <= scale/2` is the whole tolerance budget the content
    acceptance is allowed to spend, so it must be true (or the acceptance is
    unsound) and it must be nearly attained (or the acceptance is vacuous).

    The awkward case is the one the header explains: the zero-point is an
    integer, so a group whose values are not symmetric about zero has a
    representable interval that misses one end unless the scale is widened
    after the zero-point is rounded. Skipping that step costs a WHOLE step at
    the range ends, not half, so the sweep below deliberately includes
    strongly asymmetric and near-degenerate groups rather than only Gaussian
    ones.
    """
    rng = np.random.default_rng(7)
    gs = 128
    cases = {
        "gaussian": rng.standard_normal((4, 8, 4 * gs)).astype(np.float32),
        "asymmetric +": (rng.random((4, 8, 4 * gs)).astype(np.float32) * 3 + 5),
        "asymmetric -": (-rng.random((4, 8, 4 * gs)).astype(np.float32) * 3 - 5),
        "heavy tail": (rng.standard_normal((4, 8, 4 * gs)).astype(np.float32)
                       ** 5),
        "all zero": np.zeros((2, 3, 2 * gs), np.float32),
        "constant +": np.full((2, 3, 2 * gs), 0.75, np.float32),
        "constant -": np.full((2, 3, 2 * gs), -0.75, np.float32),
    }
    print("\n[u4-quant] case            max|err|      bound      err/bound")
    for name, x in cases.items():
        q, zp, scale = ef.quantise_group_affine(x, gs)
        back = ef.dequantise_affine(q, zp, scale)
        ref = x.reshape(*q.shape)
        err = np.abs(back - ref)
        bound = ef.quantisation_step_bound(scale)
        ratio = err / np.where(bound > 0, bound, 1.0)
        worst = float(ratio.max())
        print(f"[u4-quant] {name:14s} {float(err.max()):.4e}  "
              f"{float(bound.max()):.4e}  {worst:.6f}")
        assert int(q.min()) >= 0 and int(q.max()) <= 15, "codes left [0,15]"
        assert int(zp.min()) >= 0 and int(zp.max()) <= 15, "zp left [0,15]"
        assert worst <= 1.0 + _BOUND_SLACK, (
            f"{name}: an element is {worst:.6f} of a half-step out, past the "
            f"bound the representation guarantees. If the scale is not "
            f"widened after the zero-point is rounded, a value at the end of "
            f"a group's range CLIPS and lands a WHOLE step out.")
        if "constant" in name or "zero" in name:
            assert float(err.max()) == 0.0, (
                f"{name}: a group with one distinct value must be exact, "
                f"got {float(err.max()):.3e}")
    # tightness, on the case where it must be attained
    q, zp, scale = ef.quantise_group_affine(cases["gaussian"], gs)
    ratio = (np.abs(ef.dequantise_affine(q, zp, scale)
                    - cases["gaussian"].reshape(*q.shape))
             / np.where(scale > 0, ef.quantisation_step_bound(scale), 1.0))
    print(f"[u4-quant] tightness on gaussian: max ratio {float(ratio.max()):.4f}, "
          f"mean {float(ratio.mean()):.4f}")
    assert float(ratio.max()) > 0.9, (
        f"the worst error is only {float(ratio.max()):.3f} of the bound; "
        f"either the scale is far larger than the data needs, or the bound "
        f"is not the one this representation actually imposes -- a tolerance "
        f"nothing approaches accepts anything")


def test_the_filler_census_counts_what_it_served_and_catches_a_double_write():
    """The census's own red, synthetic and device-free.

    The structural acceptance below trusts `ExpertFiller.census()`. A census
    that cannot report a double-write would let (a) pass on a build that
    filled one body twice and another never.
    """
    src = lambda layer, kind: np.zeros((2, 4, 128), np.float32)  # noqa: E731
    f = ef.ExpertFiller(src, 128)
    for layer in (0, 1):
        for kind in ("gate", "up", "down"):
            f.body(layer, kind, 2, 4, 128)
    c = f.census()
    print(f"\n[fill-census] clean: {c['bodies']} bodies, layers {c['layers']}, "
          f"kinds {c['kinds']}, double_written {c['double_written']}")
    assert c["bodies"] == 6 and c["layers"] == [0, 1]
    assert c["kinds"] == ["down", "gate", "up"]
    assert c["double_written"] == {}

    f.body(0, "gate", 2, 4, 128)                      # the defect
    c2 = f.census()
    print(f"[fill-census] after a deliberate re-serve: "
          f"double_written {c2['double_written']}")
    assert c2["double_written"] == {(0, "gate"): 2}, c2["double_written"]


# ---------------------------------------------------------------------------
# Real weights from here down
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def feed():
    return gguf_feed.GgufFeed(_SHARDS)


def _moe_only_config(cfg, n_layers):
    """`cfg` with everything but the MoE geometry shrunk to nothing that
    matters, so a real-width EXPERT fill does not drag a real-width backbone
    (a 248,320-row embedding and lm_head, 2.37 GiB each) along with it.

    The expert bodies are the artifact under test and they keep every real
    dimension: num_experts 512, moe_intermediate_size 640, hidden_size 2560.
    """
    return type(cfg)(
        hidden_size=cfg.hidden_size,
        num_hidden_layers=n_layers,
        num_attention_heads=cfg.num_attention_heads,
        num_key_value_heads=cfg.num_key_value_heads,
        head_dim=cfg.head_dim,
        num_experts=cfg.num_experts,
        num_experts_per_tok=cfg.num_experts_per_tok,
        moe_intermediate_size=cfg.moe_intermediate_size,
        shared_expert_intermediate_size=64,
        hc_count=cfg.hc_count, hc_lowrank=cfg.hc_lowrank,
        ple_embed_dim=cfg.ple_embed_dim,
        ple_conv_kernel_size=cfg.ple_conv_kernel_size,
        ngram_size=cfg.ngram_size, heads_per_ngram=cfg.heads_per_ngram,
        vocab_size=512, rms_norm_eps=cfg.rms_norm_eps,
        linear_key_head_dim=cfg.linear_key_head_dim,
        linear_num_key_heads=cfg.linear_num_key_heads,
        linear_value_head_dim=cfg.linear_value_head_dim,
        linear_num_value_heads=cfg.linear_num_value_heads,
        linear_conv_kernel_dim=cfg.linear_conv_kernel_dim,
        hidden_act="silu",
        # one entry per layer: the pinned config validates the two against
        # each other (`num_hidden_layers` must equal len(layer_types))
        layer_types=["linear_attention"] * n_layers,
    )


@pytest.fixture(scope="module")
def filled(feed):
    """The serving-shape IR over `_FILL_LAYERS`, expert bodies filled from the
    real shards. Module-scoped: the GGUF dequant is ~22 s per expert-stacked
    weight and there are three per layer."""
    cfg = pwe.real_config()
    small = _moe_only_config(cfg, len(_FILL_LAYERS))
    small.ngram_total_vocab = 4096
    filler = ef.ExpertFiller(
        ef.gguf_expert_source(feed, layer_of=lambda i: _FILL_LAYERS[i]),
        ss.EXPERT_GROUP_SIZE)
    arena = ss.SparseArena()
    try:
        model, report = ss.build_serving_shape_ir(
            config=small, seq_len=8, arena=arena,
            n_layers=len(_FILL_LAYERS), filler=filler)
        yield model, report, arena, filler, small
    finally:
        arena.close()


@_skip
def test_a_every_expert_body_is_written_exactly_once(filled):
    """ACCEPTANCE (a), STRUCTURAL. The census is generated, not recited."""
    model, report, arena, filler, cfg = filled
    c = report["fill_census"]
    E, I, H = cfg.num_experts, cfg.moe_intermediate_size, cfg.hidden_size
    gs = ss.EXPERT_GROUP_SIZE

    print(f"\n[fill-a] census generated by the filler's own log:")
    print(f"  bodies         {c['bodies']}")
    print(f"  layers         {c['layers']}  (GGUF blocks {list(_FILL_LAYERS)})")
    print(f"  kinds          {c['kinds']}")
    print(f"  experts/body   {c['experts']}")
    print(f"  double_written {c['double_written']}")
    print(f"  filled bytes   {c['filled_bytes']:,} "
          f"({c['filled_bytes'] / 2**30:.3f} GiB)")
    print(f"  arena written  {report['arena_written_bytes']:,}")
    print(f"  arena on disk  {report['arena_disk_kib']:,} KiB "
          f"({report['arena_disk_kib'] / 2**20:.3f} GiB)")

    assert c["double_written"] == {}, (
        f"expert bodies served more than once: {c['double_written']}. A "
        f"double-written body dequantises to something plausible and no "
        f"numeric leg would find it.")
    assert c["kinds"] == ["down", "gate", "up"], c["kinds"]
    assert c["layers"] == list(range(len(_FILL_LAYERS))), c["layers"]
    assert c["bodies"] == 3 * len(_FILL_LAYERS), (
        f"{c['bodies']} bodies for {len(_FILL_LAYERS)} layers; expected "
        f"gate/up/down each")
    assert c["experts"] == [E], (
        f"bodies were filled at expert counts {c['experts']}, not the real "
        f"{E} -- the fill is not at real width")

    # the byte count the DECLARED shapes imply, derived here rather than
    # copied from the filler: two [E,I,H/gs,gs] u4 bodies and one
    # [E,H,I/gs,gs], their u4 zero-points, and f32 scales.
    def body_bytes(out, inn):
        groups = inn // gs
        return (E * out * groups * gs // 2          # u4 codes
                + E * out * groups * 1 // 2         # u4 zero-points
                + E * out * groups * 1 * 4)         # f32 scales
    want = len(_FILL_LAYERS) * (2 * body_bytes(I, H) + body_bytes(H, I))
    print(f"  bytes implied by the declared shapes: {want:,}")
    assert c["filled_bytes"] == want, (
        f"the filler produced {c['filled_bytes']:,} B, the declared shapes "
        f"imply {want:,} B")
    assert report["arena_written_bytes"] == want, (
        f"the arena was written {report['arena_written_bytes']:,} B for "
        f"{want:,} B of bodies")

    # ZERO UNWRITTEN BODIES: every u4 expert Constant in the graph must have a
    # placement, and no placement may still be all zeros.
    u4 = [n.get_friendly_name() for n in model.get_ordered_ops()
          if n.get_type_name() == "Constant"
          and n.get_output_element_type(0) == ss.EXPERT_DECLARED_TYPE
          and list(n.get_output_shape(0))[:1] == [E]]
    placed = {p["name"] for p in arena.placements}
    unplaced = sorted(set(u4) - placed)
    assert not unplaced, (
        f"{len(unplaced)} expert-width u4 constants have no arena placement, "
        f"so they were never filled: {unplaced[:6]}")
    # ZERO UNWRITTEN BODIES, read back OUT OF THE PAGES rather than inferred
    # from a byte counter. The fraction of non-zero bytes is the discriminator
    # that works: an unwritten body is 0% non-zero, a body carrying real u4
    # weights is nearly all non-zero, and neither figure depends on the
    # filesystem.
    #
    # IT HAS TO BE THIS RATHER THAN `arena_disk_kib`, and the reason is
    # measured. The dev host is ZFS: `st_blocks` stays at 512 B until the
    # transaction group commits (msync is not enough) and an all-zero record
    # is stored as a hole, so `disk_kib()` reported 1,899,503,616 B for
    # 2,693,529,600 B of fill -- and reports 0 KiB for 512 MiB of freshly
    # written random bytes too. See `SparseArena.disk_kib`'s docstring for the
    # three-row probe. The figure is PRINTED below and deliberately not
    # asserted.
    print(f"  {'body':<34} {'bytes':>14}  non-zero")
    weak = []
    for name in sorted(placed):
        raw, pl = arena.read_back(name)
        nz = float(np.count_nonzero(raw)) / max(len(raw), 1)
        print(f"  {name:<34} {pl['nbytes']:>14,}  {nz:6.2%}")
        if nz < 0.5:
            weak.append((name, nz))
    assert not weak, (
        f"filled bodies that are mostly or entirely zero bytes: {weak[:4]}. "
        f"An unwritten body is a block of zeros that a parity leg on other "
        f"experts would never reach.")
    print(f"  u4 expert constants {len(u4)}, all placed, none empty")
    print(f"  arena_disk_kib {report['arena_disk_kib']:,} KiB -- REPORTED, "
          f"NOT ASSERTED (ZFS; see SparseArena.disk_kib)")


@_skip
@pytest.mark.parametrize("kind", ["gate", "up", "down"])
def test_b_a_filled_body_reads_back_as_the_file_within_the_u4_rounding(
        filled, feed, kind):
    """ACCEPTANCE (b), CONTENT, at the two real geometries.

    gate/up are [512, 640, 20, 128] and down is [512, 2560, 5, 128] -- they
    differ in output width AND in group count, so a bug that assumed one
    grouping shows up on the other.

    The path is deliberately the long way round: the bytes come OUT OF THE
    ARENA PAGES the ov Constant wraps, are unpacked by the transcription of
    `src/core/gguf_repack.cpp:225`, and are dequantised by the IR's own chain
    arithmetic `(q - zp) * scale`. Nothing here consults the filler's return
    value, which would be checking the fill against itself.
    """
    model, report, arena, filler, cfg = filled
    E, I, H = cfg.num_experts, cfg.moe_intermediate_size, cfg.hidden_size
    gs = ss.EXPERT_GROUP_SIZE
    out, inn = (H, I) if kind == "down" else (I, H)
    groups = inn // gs
    layer = 0
    name = f"layer{layer}/moe/experts_{kind}"

    raw, place = arena.read_back(name + "/weight_u4")
    raw_zp, _ = arena.read_back(name + "/zero_point")
    scale = arena.scales[name + "/scale"]
    assert place["shape"] == [E, out, groups, gs], place["shape"]

    # sampled experts -- first, last and a few in between, so an off-by-one at
    # either end of the expert axis is reachable
    sample = [0, 1, E // 3, E // 2, E - 2, E - 1]
    src = ef.gguf_expert_source(feed, layer_of=lambda i: _FILL_LAYERS[i])
    ref_all = src(layer, kind)
    assert ref_all.shape == (E, out, inn), ref_all.shape

    per_expert = out * groups * gs
    worst_err = worst_ratio = 0.0
    for e in sample:
        lo = e * per_expert
        codes = ef.unpack_u4(raw[lo // 2:(lo + per_expert) // 2], per_expert)
        codes = codes.reshape(out, groups, gs)
        zlo = e * out * groups
        zcodes = ef.unpack_u4(raw_zp[zlo // 2:(zlo + out * groups) // 2],
                              out * groups).reshape(out, groups, 1)
        back = ef.dequantise_affine(codes, zcodes, scale[e])
        ref = ref_all[e].reshape(out, groups, gs)
        err = np.abs(back - ref)
        bound = ef.quantisation_step_bound(scale[e])
        ratio = err / np.where(bound > 0, bound, 1.0)
        worst_err = max(worst_err, float(err.max()))
        worst_ratio = max(worst_ratio, float(ratio.max()))

    print(f"\n[fill-b] {kind:5s} [{E}, {out}, {groups}, {gs}]  "
          f"experts {sample}")
    print(f"  max |arena-readback - gguf f32|   {worst_err:.6e}")
    print(f"  max err / (scale/2)               {worst_ratio:.6f}   "
          f"(the u4 representation's own rounding; slack {_BOUND_SLACK})")
    assert worst_ratio <= 1.0 + _BOUND_SLACK, (
        f"{kind}: a weight read back from the arena is {worst_ratio:.6f} of a "
        f"half-step away from the file. The u4 representation is entitled to "
        f"scale/2 and no more; past it, the fill is not a rounding, it is a "
        f"different number.")
    assert worst_ratio > 0.5, (
        f"{kind}: the worst deviation is only {worst_ratio:.3f} of the "
        f"half-step bound. Either the scales are far wider than the data or "
        f"the read-back is not reading the data -- a tolerance nothing "
        f"approaches accepts anything.")

    # and OpenVINO's own reading of those same pages agrees with the C++ rule
    e = sample[0]
    sub = raw[e * per_expert // 2:(e + 1) * per_expert // 2]
    t = ov.Tensor(np.ascontiguousarray(sub), ov.Shape([out, groups, gs]),
                  ov.Type.u4)
    m = ov.Model([opv.result(opv.convert(opv.constant(t), ov.Type.f32))], [],
                 "readback")
    ov_codes = np.asarray(
        list(ov.Core().compile_model(m, "CPU")({}).values())[0]).astype(np.uint8)
    cpp_codes = ef.unpack_u4(sub, per_expert).reshape(out, groups, gs)
    mism = int((ov_codes != cpp_codes).sum())
    print(f"  OpenVINO vs gguf_repack.cpp:225 on expert {e}: {mism} of "
          f"{per_expert:,} codes differ")
    assert mism == 0, (
        f"{mism} codes differ between OpenVINO's u4 read and the C++ rule on "
        f"real filled data")


# ---------------------------------------------------------------------------
# (c) end to end -- one filled MoE layer piece, executed
# ---------------------------------------------------------------------------

def _expert_piece_model(arena, cfg, E, I, H, M, filler):
    """The tiled expert math over filled bodies, as a standalone model.

    input  x  [E, M, H]
    output y  [E, M, H] = (swish(x @ gate^T) * (x @ up^T)) @ down^T

    This is `emit_moe_tiled`'s expert half -- the three `_compressed_expert`
    chains and the three MatMuls they feed -- lifted out so it can be executed
    without a router, a shared expert or a 248,320-row lm_head.
    """
    x = opv.parameter([E, M, H], ov.Type.f32)
    x.set_friendly_name("x")
    gate = ss._compressed_expert(arena, E, I, H, "piece/experts_gate",
                                 filler, 0, "gate")
    up = ss._compressed_expert(arena, E, I, H, "piece/experts_up",
                               filler, 0, "up")
    down = ss._compressed_expert(arena, E, H, I, "piece/experts_down",
                                 filler, 0, "down")
    g = opv.swish(opv.matmul(x, gate, transpose_a=False, transpose_b=True))
    u = opv.matmul(x, up, transpose_a=False, transpose_b=True)
    y = opv.matmul(opv.multiply(g, u), down,
                   transpose_a=False, transpose_b=True)
    r = opv.result(y)
    r.set_friendly_name("y")
    return ov.Model([r], [x], "filled_expert_piece")


def _numpy_expert_piece(x, gate, up, down):
    """The same arithmetic in f64: swish(x@gate^T) * (x@up^T) then @ down^T."""
    a = np.einsum("emh,eih->emi", x.astype(np.float64), gate.astype(np.float64))
    a = a / (1.0 + np.exp(-a))                       # swish == x * sigmoid(x)
    b = np.einsum("emh,eih->emi", x.astype(np.float64), up.astype(np.float64))
    return np.einsum("emi,ehi->emh", a * b, down.astype(np.float64))


@_skip
def test_c_a_filled_expert_piece_executes_and_the_two_distances_separate(feed):
    """ACCEPTANCE (c), END TO END, and the comparison is deliberately split.

    Against the DEQUANTISED-u4 weights -- the exact values the filled
    constants represent -- the executed piece must be at the f32 floor. That
    leg is the plumbing: packing order, group layout, zero-points, scales, the
    Convert/Subtract/Multiply/Reshape chain. It has no quantisation budget to
    hide in, so a swapped nibble pair or a transposed group fails it outright.

    Against the RAW f32 GGUF weights the difference is the quantisation cost,
    and it is REPORTED with the bound that predicts it rather than asserted
    against a threshold somebody picked. Blending the two comparisons -- which
    is what "compare the filled piece to the reference" naively means -- would
    let a real packing bug hide inside the quantisation budget.

    Geometry: 8 REAL experts at REAL width (I=640, H=2560), which is the piece
    that fits in a CPU run; the fill itself is accepted at all 512 by (a).
    """
    cfg = pwe.real_config()
    E, I, H, M = 8, cfg.moe_intermediate_size, cfg.hidden_size, 16
    gs = ss.EXPERT_GROUP_SIZE
    layer = 0

    src = ef.gguf_expert_source(feed, layer_of=lambda i: layer)
    raw = {k: np.ascontiguousarray(src(layer, k)[:E]) for k in
           ("gate", "up", "down")}
    filler = ef.ExpertFiller(lambda l, k: raw[k], gs)

    arena = ss.SparseArena(capacity_bytes=1 << 34)
    try:
        model = _expert_piece_model(arena, cfg, E, I, H, M, filler)
        compiled = ov.Core().compile_model(model, "CPU")
        rng = np.random.default_rng(5)
        x = (rng.standard_normal((E, M, H)) * 0.05).astype(np.float32)
        y = np.asarray(list(compiled({"x": x}).values())[0])

        # the values the filled constants actually represent
        deq = {}
        for k in ("gate", "up", "down"):
            out, inn = (H, I) if k == "down" else (I, H)
            name = f"piece/experts_{k}"
            buf, place = arena.read_back(name + "/weight_u4")
            bz, _ = arena.read_back(name + "/zero_point")
            groups = inn // gs
            q = ef.unpack_u4(buf, E * out * groups * gs).reshape(
                E, out, groups, gs)
            z = ef.unpack_u4(bz, E * out * groups).reshape(E, out, groups, 1)
            deq[k] = ef.dequantise_affine(
                q, z, arena.scales[name + "/scale"]).reshape(E, out, inn)

        y_deq = _numpy_expert_piece(x, deq["gate"], deq["up"], deq["down"])
        y_raw = _numpy_expert_piece(x, raw["gate"], raw["up"], raw["down"])

        d_plumbing = float(np.max(np.abs(y - y_deq)))
        d_quant = float(np.max(np.abs(y - y_raw)))
        scale_y = float(np.max(np.abs(y_raw)))
        # the f32 floor for this contraction: f32 eps, the magnitude of the
        # result, and the length of the two chained contractions
        floor = float(np.finfo(np.float32).eps) * scale_y * np.sqrt(H + I)

        print(f"\n[fill-c] E={E} (real experts) M={M} I={I} H={H}, CPU")
        print(f"  |executed - dequantised-u4 reference|  {d_plumbing:.6e}")
        print(f"  f32 floor for this contraction          {floor:.6e}")
        print(f"  |executed - raw f32 reference|          {d_quant:.6e}")
        print(f"  output magnitude                        {scale_y:.6e}")
        print(f"  quantisation cost, relative             "
              f"{d_quant / scale_y:.4f}")

        assert d_plumbing <= floor, (
            f"the executed piece is {d_plumbing:.3e} from the values its own "
            f"constants represent, past the {floor:.3e} f32 floor. That is a "
            f"PLUMBING defect -- packing order, group layout, zero-points or "
            f"scales -- not quantisation: this comparison has no "
            f"quantisation in it.")
        assert d_quant > d_plumbing, (
            "the raw-f32 and dequantised-u4 references are equidistant, so "
            "the fill is not quantising anything and one of the two "
            "references is not what it claims to be")
    finally:
        arena.close()
