"""CF-COUNTS: a `file:line` citation in tracked prose must resolve to the code
it names.

WHY THIS FILE EXISTS (REVIEW 2a45349 F4, 2026-09-12). This repository's stated
standard is grep-verified citations, and the batch that invented CF-MANIFESTSHA
to stop unenforced claims in the manifest shipped four drifted citations of its
own:

    `gated_delta_state_table.`  cited :3196, the prefix test is at :3195
    `key_cache.`                cited :3200, the prefix test is at :3199
    `value_cache.`              cited :3200, the prefix test is at :3199
    `element_type().size()`     cited  :603, the expression is at  :604

None broke a gate. All four would mislead the next reader, and they drifted for
the ordinary reason: somebody inserted a line above them. A citation written by
hand is correct until the next edit; that is not a property worth having.

The reviewer generalised the class into the PROSE-CLAIM LAW's clause 2 --
"counts are generated by their defining gate at commit time, never recited" --
and a line number is a count.

--------------------------------------------------------------------------
THE TWO LEGS, and what each can and cannot do
--------------------------------------------------------------------------

LEG 1, ANCHORED. The strong one. A row here names the citation AS WRITTEN in
some tracked file, the file it points into, and an ANCHOR -- a substring of the
cited line, which is the thing the author actually meant. The gate resolves the
anchor (asserting it matches exactly one line) and checks the written number
against the resolved one. Both halves can fail usefully: an anchor that matches
nothing means the cited code was deleted or rewritten; an anchor that matches
two lines means the citation identifies nothing; a resolved line number that
disagrees with the prose is the drift above.

This leg is not automatic and cannot be: only a human knows which line a
sentence meant. It covers the citations that carry contract weight -- the OTD
handshake, the paged-port inventory, the slice-bytes constant, the slot
ceiling. `tests/python/test_serving_shape.py` goes further for its own
inventory and does not write the numbers down at all: `_PAGED_PORTS` derives
every one of its thirteen citations from an anchor at import.

LEG 2, RESOLVABILITY. The weak, total one. Every `file:line` in tracked prose
that resolves unambiguously to a file in this repository must point at a line
that EXISTS. This cannot see a one-line drift -- that is exactly what LEG 1 is
for -- but it does catch a citation into a file that has shrunk, or been
renamed, or never existed, and it costs nothing to run over the whole tree.

WHAT IS DELIBERATELY NOT ASSERTED: citations into OTHER repositories.
`docs/research-freetoken.md` cites FreeToken's own `ple.py` at lines 465-478
and four more places -- FreeToken's files (pinned @ 505477ab), not this
repository's `tools/q4e/ple.py`, which is 217 lines long. A basename match
across a repository boundary is a false positive with a confident error
message, the worst kind, so LEG 2 resolves a citation only when the basename
is unique among tracked files AND the citing file is not on the
foreign-citation list below. That list is short and explicit, because "this
citation points somewhere else" should cost a line of prose rather than
silently weakening the gate.

(The first run of LEG 2 failed on THIS DOCSTRING, which had written that
example out as a literal `file:line` and thereby made a claim about
`tools/q4e/ple.py` that its 217 lines cannot satisfy. The scan was right and
the prose was wrong, which is the outcome this file exists to produce.)

Device-free, no shards, no card: it reads text.
"""
import re
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]

_CITE = re.compile(r"\b([A-Za-z0-9_][A-Za-z0-9_./-]*\.(?:cpp|h|py)):(\d+)(?:-(\d+))?")

# Files whose `file:line` citations point into OTHER repositories. A citation
# in one of these is skipped by LEG 2 rather than resolved against a
# same-named file here, which would be a false positive with a confident error
# message -- the worst kind.
_FOREIGN_CITATION_FILES = {
    "docs/research-freetoken.md",       # FreeToken's tree, pinned @ 505477ab
}

# LEG 1. (citing file, the citation exactly as written there, the file it
# points into, an anchor substring of the cited line).
#
# ADD A ROW when a citation starts carrying weight -- when a reader would act
# on it. Do not add rows mechanically; an anchor nobody checked is decoration
# with a test around it.
_ANCHORED = [
    # -- the OTD / expert-slot handshake, both sides ------------------------
    ("tools/q4e/serving_shape.py", "backend_ov.cpp:577",
     "src/exec/backend_ov.cpp", "std::optional<SlotPoolIr> slot_pool_from_ir"),
    ("tools/q4e/serving_shape.py", "backend_ov.cpp:566-569",
     "src/exec/backend_ov.cpp", "this function never guesses"),
    ("tests/python/test_serving_shape.py", "backend_ov.cpp:585",
     "src/exec/backend_ov.cpp",
     'if (tname.find("moe") == std::string::npos) continue;'),
    ("tests/python/test_serving_shape.py", "backend_ov.cpp:604",
     "src/exec/backend_ov.cpp",
     "per_expert_bytes += elems * konst->get_element_type().size();"),
    ("tools/q4e/serving_shape.py", "backend_ov.cpp:600-604",
     "src/exec/backend_ov.cpp",
     "per_expert_bytes += elems * konst->get_element_type().size();"),
    # -- the constants the residency arithmetic is checked against ----------
    ("tests/python/test_serving_shape.py", "flash_next_offload.h:45",
     "src/exec/flash_next_offload.h", "kFlashNextSliceBytes  = 2'457'600"),
    ("tools/q4e/serving_shape.py", "exec/flash_next_offload.h:45",
     "src/exec/flash_next_offload.h", "kFlashNextSliceBytes  = 2'457'600"),
    ("tests/python/test_serving_shape.py", "fit.h:95",
     "src/exec/fit.h", "inline uint64_t expert_slot_bytes("),
    ("tools/q4e/serving_shape.py", "src/exec/fit.h:95",
     "src/exec/fit.h", "inline uint64_t expert_slot_bytes("),
    # -- the port names the serving path declares and feeds -----------------
    ("tests/python/test_serving_shape.py", "backend_ov.cpp:98",
     "src/exec/backend_ov.cpp", 'kPositionIds   = "position_ids"'),
    ("tests/python/test_serving_shape.py", "src/exec/ngram_row_ids.h:59",
     "src/exec/ngram_row_ids.h", "int num_ngram_heads() const"),
    # -- the `_c` binding CF-RESIDENT's ast scan found ----------------------
    ("tools/q4e/serving_shape.py", "backbone.py:70",
     "tools/q4e/backbone.py", "from .gdn import _c"),
]


def _resolve(cited_path, anchor):
    """The ONE line of `cited_path` containing `anchor`, or a stated failure."""
    p = REPO_ROOT / cited_path
    assert p.is_file(), f"cited file {cited_path} does not exist"
    hits = [i for i, line in enumerate(p.read_text().splitlines(), 1)
            if anchor in line]
    return hits


@pytest.mark.parametrize(
    "citing,written,cited,anchor", _ANCHORED,
    ids=[f"{c.split('/')[-1]}:{w}" for c, w, _, anchor in _ANCHORED])
def test_an_anchored_citation_names_the_line_its_anchor_resolves_to(
        citing, written, cited, anchor):
    """LEG 1. The written number must equal the resolved one."""
    src = (REPO_ROOT / citing)
    assert src.is_file(), f"citing file {citing} does not exist"
    text = src.read_text()
    assert written in text, (
        f"{citing} no longer contains the citation {written!r}. Either it was "
        f"edited (update this row) or removed (delete this row) -- a registry "
        f"row for a citation that is not there gates nothing.")

    hits = _resolve(cited, anchor)
    assert len(hits) == 1, (
        f"{citing} cites {written}; its anchor {anchor!r} matches "
        f"{len(hits)} lines of {cited}"
        + (f" ({hits[:6]})" if hits else " -- the cited code is gone")
        + ". An anchor must identify exactly one line.")
    line = hits[0]
    m = re.fullmatch(r"([A-Za-z0-9_./-]+):(\d+)(?:-(\d+))?", written)
    assert m, f"{written!r} is not a file:line citation"
    start = int(m.group(2))
    end = int(m.group(3)) if m.group(3) else start
    assert start <= line <= end, (
        f"CITATION DRIFT. {citing} writes {written}, but its anchor\n"
        f"    {anchor}\n"
        f"is at {Path(cited).name}:{line}. Correct the prose to "
        f"{Path(cited).name}:{line}"
        + (f" (or widen the range to cover it)" if end != start else "")
        + ". This is REVIEW 2a45349 F4's class: nothing is broken, and the "
          "next reader is sent to the wrong line.")


def test_the_anchored_registry_is_not_empty():
    """A registry of nothing passes every row above vacuously."""
    assert len(_ANCHORED) >= 10, f"only {len(_ANCHORED)} anchored citations"
    citing = {c for c, _, _, _ in _ANCHORED}
    assert len(citing) >= 2, f"only {citing} covered; the registry is too narrow"


def _tracked_files():
    r = subprocess.run(["git", "-C", str(REPO_ROOT), "ls-files"],
                       capture_output=True, text=True, timeout=60)
    assert r.returncode == 0, f"git ls-files failed: {r.stderr[:200]}"
    return r.stdout.split()


def _in_git_worktree():
    try:
        r = subprocess.run(["git", "-C", str(REPO_ROOT), "rev-parse",
                            "--is-inside-work-tree"],
                           capture_output=True, text=True, timeout=10)
        return r.returncode == 0 and r.stdout.strip() == "true"
    except Exception:
        return False


@pytest.mark.skipif(not _in_git_worktree(),
                    reason="not a git work tree (a staged tree has no .git); "
                           "the tracked-file list needs the index")
def test_every_resolvable_citation_points_at_a_line_that_exists():
    """LEG 2, total and weak. Counts are PRINTED, never written down: the
    scanned population is whatever `git ls-files` says today."""
    tracked = _tracked_files()
    by_name = {}
    for t in tracked:
        by_name.setdefault(Path(t).name, []).append(t)

    scanned = resolved = foreign = untracked = ambiguous = 0
    bad = []
    for t in tracked:
        if not t.endswith((".py", ".md", ".cpp", ".h", ".txt")):
            continue
        try:
            src = (REPO_ROOT / t).read_text(errors="replace")
        except OSError:
            continue
        for m in _CITE.finditer(src):
            scanned += 1
            if t in _FOREIGN_CITATION_FILES:
                foreign += 1
                continue
            cands = by_name.get(Path(m.group(1)).name, [])
            if not cands:
                # names a file this repository does not track -- the pinned
                # transformers reference, an OpenVINO header, a plugin source
                untracked += 1
                continue
            if len(cands) > 1:
                ambiguous += 1
                continue
            target = REPO_ROOT / cands[0]
            n = len(target.read_text(errors="replace").splitlines())
            hi = int(m.group(3) or m.group(2))
            resolved += 1
            if hi > n or int(m.group(2)) < 1:
                line = src.count("\n", 0, m.start()) + 1
                bad.append((t, line, m.group(0), cands[0], n))

    print(f"\n[cite-resolve] {scanned} file:line citations in tracked prose")
    print(f"  {resolved:>4} resolved to a tracked file and range-checked")
    print(f"  {untracked:>4} name a file this repo does not track "
          f"(the pin, OpenVINO, plugin sources) -- out of reach, not skipped")
    print(f"  {ambiguous:>4} basename matches several tracked files")
    print(f"  {foreign:>4} in files that cite another repository "
          f"({', '.join(sorted(_FOREIGN_CITATION_FILES))})")
    print(f"  {len(_ANCHORED):>4} ANCHORED: the line NUMBER is checked, not "
          f"merely that the line exists")
    assert resolved + untracked + ambiguous + foreign == scanned
    assert not bad, (
        "citation(s) pointing past the end of the file they name:\n"
        + "\n".join(f"  {t}:{ln}  {cite}  ->  {dest} has {n} lines"
                    for t, ln, cite, dest, n in bad))


def test_the_resolvability_scan_detects_a_line_past_the_end():
    """LEG 2's own red, in tree. The scan's arithmetic, applied to a citation
    that cannot resolve, must reject it -- otherwise the cell above passes for
    files it never really checked."""
    n = len((REPO_ROOT / "tools" / "q4e" / "ple.py").read_text().splitlines())
    for cite, want_bad in ((f"ple.py:{n}", False), (f"ple.py:{n + 1}", True),
                           (f"ple.py:1-{n + 400}", True), ("ple.py:1", False)):
        m = _CITE.fullmatch(cite)
        assert m, cite
        hi = int(m.group(3) or m.group(2))
        assert (hi > n) == want_bad, (
            f"{cite} against a {n}-line file: expected "
            f"{'rejected' if want_bad else 'accepted'}")
    print(f"[cite-resolve] red probe: tools/q4e/ple.py is {n} lines; a "
          f"citation at {n + 1} is rejected, at {n} accepted")
