#!/usr/bin/env python3
"""Render the acceptance enumeration into DESIGN.md and docs/release-checklist.md
(docs/design-0.3.1-test-ladder.md §3: "DESIGN §5.1 and the checklist are
generated"). tests/acceptance/cells.json is the single source; this script
only ever replaces text between its own markers, never the prose around it.

Increment 3 (§8) adds a `references` schema check ahead of rendering: every
cell must carry a `references` key (a list, possibly empty, or JSON null
meaning "not yet filled"); every reference in a non-null list must carry all
of REFERENCE_FIELDS and a recognized `direction`; and, where a cell declares
`metric_qualifiers`, every reference's metric name must contain a token from
each declared group (the naming rule that keeps a card_class: both cell's
metrics from silently averaging two cards, and keeps the tier cell's metrics
naming their arm). A schema error refuses to render, in both modes -- a
generated file built from an invalid enumeration is not something to check
in. References render beside their cell, in both DESIGN.md's §5.1 span and
docs/release-checklist.md; an empty or null list renders as "not yet filled"
or nothing at all, never a rendering error.

    tools/acceptance_manifest.py            regenerate both files in place
    tools/acceptance_manifest.py --check    regenerate and diff; exit != 0 on drift
"""
import argparse
import difflib
import json
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CELLS_JSON = os.path.join(REPO_ROOT, "tests", "acceptance", "cells.json")
DESIGN_MD = os.path.join(REPO_ROOT, "DESIGN.md")
CHECKLIST_MD = os.path.join(REPO_ROOT, "docs", "release-checklist.md")

MARK_BEGIN = "<!-- BEGIN GENERATED by tools/acceptance_manifest.py; verify with its check mode -->"
MARK_END = "<!-- END GENERATED by tools/acceptance_manifest.py -->"

# Mandatory fields of one cells.json reference entry
# (docs/design-0.3.1-test-ladder.md §8.1). tests/acceptance/run.py carries
# the same list as a second, cheap check at run time -- this one is the
# schema's actual authority, run at --check time over every cell, filled or
# not.
REFERENCE_FIELDS = ("metric", "value", "gate_at", "unit", "direction",
                     "samples", "spread_pct", "config", "prompt_tokens",
                     "design", "measured", "binary")
DIRECTIONS = ("lower-is-worse", "higher-is-worse")


def load_cells():
    with open(CELLS_JSON, encoding="utf-8") as f:
        cells = json.load(f)
    if not isinstance(cells, list):
        raise SystemExit(f"{CELLS_JSON}: expected a JSON array of cells")
    return cells


def validate_cells(cells):
    """Schema checks over `references` (§8.1) beyond plain JSON well-
    formedness. Returns a list of error strings; empty means valid. Never
    raises on a well-formed-but-wrong document -- that is what makes it
    testable against a fixture without a subprocess.
    """
    errors = []
    for cell in cells:
        name = cell.get("name", "<unnamed>")

        # expected_skips (docs/design-0.3.1-test-ladder.md §2's amendment):
        # a declared skip is pre-named, so its shape has to be checked here
        # too, not just trusted at run.py's runtime. Checked independent of
        # `references` below -- a cell can have one, both, or neither.
        seen_checks = set()
        for es in cell.get("expected_skips") or []:
            missing = [f for f in ("check", "reason") if f not in es]
            if missing:
                errors.append(f"{name}: expected_skips entry missing field(s): "
                              f"{', '.join(missing)}")
                continue
            if es["check"] in seen_checks:
                errors.append(f"{name}/{es['check']}: duplicate expected_skips entry")
            seen_checks.add(es["check"])

        # metric_qualifiers shape (Increment-3 review, 2026-09-05, item 6):
        # a non-empty list of non-empty lists of non-empty strings. Checked
        # independent of `references` too -- the field can be present on a
        # cell whose references are still `null` (tier-reference-cell and
        # depth-ladder both declare it now, ahead of the fill).
        qualifiers = cell.get("metric_qualifiers")
        if qualifiers is not None:
            if not isinstance(qualifiers, list) or not qualifiers:
                errors.append(f"{name}: metric_qualifiers must be a non-empty list of groups")
            else:
                for group in qualifiers:
                    if (not isinstance(group, list) or not group
                            or not all(isinstance(t, str) and t for t in group)):
                        errors.append(f"{name}: metric_qualifiers group {group!r} must be "
                                      "a non-empty list of non-empty strings")

        if "references" not in cell:
            errors.append(f"{name}: missing \"references\" (must be a list, or null "
                          "if not yet filled)")
            continue
        references = cell["references"]
        if references is None:
            continue  # "not yet filled" -- nothing to check yet (§8's amendment)
        if not isinstance(references, list):
            errors.append(f"{name}: \"references\" must be a list or null, "
                          f"got {type(references).__name__}")
            continue

        seen_metrics = set()
        for ref in references:
            metric = ref.get("metric", "<unnamed metric>")
            missing = [f for f in REFERENCE_FIELDS if f not in ref]
            if missing:
                errors.append(f"{name}/{metric}: missing field(s): {', '.join(missing)}")
                continue
            if ref["direction"] not in DIRECTIONS:
                errors.append(f"{name}/{metric}: direction must be one of "
                              f"{DIRECTIONS}, got {ref['direction']!r}")
            if not _is_number(ref["value"]):
                errors.append(f"{name}/{metric}: value must be a number, got {ref['value']!r}")
            # gate_at null is the report-only reference (§8.9): recorded and
            # printed by run.py, never compared. Otherwise it is the number
            # run.py compares against, and a string here would compare as
            # text -- refuse it at --check time, not on the first real run.
            if ref["gate_at"] is not None and not _is_number(ref["gate_at"]):
                errors.append(f"{name}/{metric}: gate_at must be a number or null "
                              f"(report-only), got {ref['gate_at']!r}")
            if metric in seen_metrics:
                errors.append(f"{name}/{metric}: duplicate reference for this metric")
            seen_metrics.add(metric)
            if qualifiers and isinstance(qualifiers, list):
                # Naming rule (§8.7 "both cards under one name" / the tier
                # cell's arm): the metric must carry at least one token from
                # EVERY declared qualifier group, so a card_class: both cell
                # cannot register an unqualified "decode" that would
                # silently average two cards, and the tier cell's metrics
                # each name their arm. Matched on '-'-separated TOKENS of the
                # metric name, not substrings (item 6, 2026-09-05 review):
                # a plain "token in metric" substring test would let "u8"
                # match "decode-large-u8i4" too, which is exactly the
                # ambiguity this rule exists to refuse.
                metric_tokens = set(metric.split("-"))
                for group in qualifiers:
                    if not (isinstance(group, list) and any(t in metric_tokens for t in group)):
                        errors.append(
                            f"{name}/{metric}: does not carry one of {group} "
                            "(metric_qualifiers naming rule)")
    return errors


def _is_number(x):
    return isinstance(x, (int, float)) and not isinstance(x, bool)


def gate_phrase(ref):
    """'gate <direction> at <gate_at> <unit>' for a gated reference, or
    'report only, not gated' for the §8.9 form -- one place, so the §5.1
    span and the checklist cannot disagree about which a reference is."""
    if ref["gate_at"] is None:
        return "report only, not gated"
    return f"gate {ref['direction']} at {ref['gate_at']} {ref['unit']}"


def cell_phrase(cell):
    phrase = f"`{cell['name']}` gates {cell['gates']}"
    if cell.get("reports"):
        phrase += f" (reports {cell['reports']})"
    references = cell.get("references")
    if references is None:
        phrase += " (references: not yet filled)"
    elif references:
        rendered = "; ".join(
            f"{r['metric']} {r['value']} {r['unit']} ({gate_phrase(r)})"
            for r in references)
        phrase += f" (references: {rendered})"
    expected_skips = cell.get("expected_skips")
    if expected_skips:
        rendered = "; ".join(f"{es['check']} ({es['reason']})" for es in expected_skips)
        phrase += f" (expected skip: {rendered})"
    if cell.get("increment"):
        phrase += f" [runner lands in Increment {cell['increment']}]"
    return phrase


def render_design_span(cells):
    return "; ".join(cell_phrase(c) for c in cells)


def render_checklist(cells):
    lines = []
    lines.append("# Release checklist")
    lines.append("")
    lines.append("Generated from `tests/acceptance/cells.json` by "
                 "`tools/acceptance_manifest.py`. Do not hand-edit the "
                 "generated span; regenerate it and commit the result. "
                 "`--check` regenerates and diffs, failing "
                 "`acceptance-enumeration` when this file has drifted from "
                 "the enumeration.")
    lines.append("")
    lines.append("Run the acceptance target before tagging a release:")
    lines.append("")
    lines.append("    tests/acceptance/run.py --all --allow-skip <cell> ...")
    lines.append("")
    lines.append("Every 77 (skip) must be named on that command line, or the "
                 "run does not count as a release gate (docs/design-0.3.1-test-ladder.md §2).")
    lines.append("")
    lines.append("## Cells")
    lines.append("")
    for c in cells:
        design = ", ".join(c.get("design", []))
        runner = "external" if c.get("external") else c.get("runner", {}).get("cmd", "?")
        lines.append(f"- [ ] `{c['name']}` -- {runner} ({design})")
        if c.get("flags"):
            lines.append(f"      flags: {c['flags']}")
        lines.append(f"      gates: {c['gates']}")
        if c.get("reports"):
            lines.append(f"      reports: {c['reports']}")
        references = c.get("references")
        if references is None:
            lines.append("      references: not yet filled")
        elif references:
            for r in references:
                lines.append(f"      reference: {r['metric']} = {r['value']} {r['unit']} "
                             f"({gate_phrase(r)}, "
                             f"{r['samples']} sample(s), {r['spread_pct']}% spread) "
                             f"-- {r['config']}, {r['prompt_tokens']} prompt tokens, "
                             f"{r['design']}, measured {r['measured']}, {r['binary']}")
        expected_skips = c.get("expected_skips")
        if expected_skips:
            for es in expected_skips:
                lines.append(f"      expected skip: {es['check']} (declared: {es['reason']}; "
                             "pre-named -- --allow-skip naming it is an error)")
        if c.get("timeout_seconds"):
            lines.append(f"      timeout: {c['timeout_seconds']}s "
                         "(the generated per-cell ctest test's own TIMEOUT; "
                         "run.py --all enforces the same figure itself)")
        if c.get("increment"):
            lines.append(f"      runner: not yet in the tree (Increment {c['increment']}); the cell cannot run")
        if c.get("external"):
            ext = c["external"]
            lines.append(f"      external: env {ext['env']}; unset -> "
                         f"SKIPPED external-harness-not-configured "
                         f"(reference {ext.get('reference_score', '?')})")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def splice(text, span, path):
    begin = text.find(MARK_BEGIN)
    end = text.find(MARK_END)
    if begin == -1 or end == -1 or end < begin:
        raise SystemExit(f"{path}: generated markers not found or out of order; "
                         "run without --check once to seed them")
    begin_content = begin + len(MARK_BEGIN)
    return text[:begin_content] + span + text[end:]


def whole_generated_file(span):
    return MARK_BEGIN + "\n" + span + MARK_END + "\n"


def read(path):
    if not os.path.exists(path):
        return ""
    with open(path, encoding="utf-8") as f:
        return f.read()


def write(path, content):
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def diff(label, before, after):
    if before == after:
        return []
    return list(difflib.unified_diff(before.splitlines(keepends=True),
                                      after.splitlines(keepends=True),
                                      fromfile=f"{label} (on disk)",
                                      tofile=f"{label} (regenerated)"))


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--check", action="store_true",
                   help="regenerate and diff instead of writing; exit != 0 on drift")
    args = p.parse_args()

    cells = load_cells()

    schema_errors = validate_cells(cells)
    if schema_errors:
        for e in schema_errors:
            print(f"acceptance-manifest: schema error: {e}", file=sys.stderr)
        return 1

    design_span = render_design_span(cells) + " "
    checklist_content = whole_generated_file(render_checklist(cells))

    design_before = read(DESIGN_MD)
    if MARK_BEGIN not in design_before:
        raise SystemExit(f"{DESIGN_MD}: no {MARK_BEGIN!r} marker found")
    design_after = splice(design_before, design_span, DESIGN_MD)

    checklist_before = read(CHECKLIST_MD)
    checklist_after = checklist_content

    if args.check:
        d1 = diff("DESIGN.md", design_before, design_after)
        d2 = diff("docs/release-checklist.md", checklist_before, checklist_after)
        if not d1 and not d2:
            print("acceptance-manifest: DESIGN.md and docs/release-checklist.md "
                 "agree with tests/acceptance/cells.json")
            return 0
        for d in (d1, d2):
            if d:
                sys.stdout.writelines(d)
        print("\nacceptance-manifest: drift detected; run "
             "tools/acceptance_manifest.py to regenerate", file=sys.stderr)
        return 1

    write(DESIGN_MD, design_after)
    write(CHECKLIST_MD, checklist_after)
    print("acceptance-manifest: regenerated DESIGN.md and docs/release-checklist.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
