#!/usr/bin/env python3
"""Render the acceptance enumeration into DESIGN.md and docs/release-checklist.md
(docs/design-0.3.1-test-ladder.md §3: "DESIGN §5.1 and the checklist are
generated"). tests/acceptance/cells.json is the single source; this script
only ever replaces text between its own markers, never the prose around it.

    tools/acceptance_manifest.py            regenerate both files in place
    tools/acceptance_manifest.py --check    regenerate and diff; exit != 0 on drift
"""
import argparse
import difflib
import json
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CELLS_JSON = os.path.join(REPO_ROOT, "tests", "acceptance", "cells.json")
DESIGN_MD = os.path.join(REPO_ROOT, "DESIGN.md")
CHECKLIST_MD = os.path.join(REPO_ROOT, "docs", "release-checklist.md")

MARK_BEGIN = "<!-- BEGIN GENERATED by tools/acceptance_manifest.py; verify with its check mode -->"
MARK_END = "<!-- END GENERATED by tools/acceptance_manifest.py -->"


def load_cells():
    with open(CELLS_JSON, encoding="utf-8") as f:
        cells = json.load(f)
    if not isinstance(cells, list):
        raise SystemExit(f"{CELLS_JSON}: expected a JSON array of cells")
    return cells


def cell_phrase(cell):
    phrase = f"`{cell['name']}` gates {cell['gates']}"
    if cell.get("reports"):
        phrase += f" (reports {cell['reports']})"
    if cell.get("increment"):
        phrase += f" [runner lands in Increment {cell['increment']}]"
    return phrase


def render_design_span(cells):
    return "; ".join(cell_phrase(c) for c in cells)


def render_checklist(cells):
    lines = []
    lines.append("# Release checklist")
    lines.append("")
    lines.append("Generated from `tests/acceptance/cells.json` by "
                 "`tools/acceptance_manifest.py`. Do not hand-edit the "
                 "generated span; regenerate it and commit the result. "
                 "`--check` regenerates and diffs, failing "
                 "`acceptance-enumeration` when this file has drifted from "
                 "the enumeration.")
    lines.append("")
    lines.append("Run the acceptance target before tagging a release:")
    lines.append("")
    lines.append("    tests/acceptance/run.py --all --allow-skip <cell> ...")
    lines.append("")
    lines.append("Every 77 (skip) must be named on that command line, or the "
                 "run does not count as a release gate (docs/design-0.3.1-test-ladder.md §2).")
    lines.append("")
    lines.append("## Cells")
    lines.append("")
    for c in cells:
        design = ", ".join(c.get("design", []))
        runner = "external" if c.get("external") else c.get("runner", {}).get("cmd", "?")
        lines.append(f"- [ ] `{c['name']}` -- {runner} ({design})")
        if c.get("flags"):
            lines.append(f"      flags: {c['flags']}")
        lines.append(f"      gates: {c['gates']}")
        if c.get("reports"):
            lines.append(f"      reports: {c['reports']}")
        if c.get("timeout_seconds"):
            lines.append(f"      timeout: {c['timeout_seconds']}s "
                         "(the generated per-cell ctest test's own TIMEOUT; "
                         "run.py --all enforces the same figure itself)")
        if c.get("increment"):
            lines.append(f"      runner: not yet in the tree (Increment {c['increment']}); the cell cannot run")
        if c.get("external"):
            ext = c["external"]
            lines.append(f"      external: env {ext['env']}; unset -> "
                         f"SKIPPED external-harness-not-configured "
                         f"(reference {ext.get('reference_score', '?')})")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def splice(text, span, path):
    begin = text.find(MARK_BEGIN)
    end = text.find(MARK_END)
    if begin == -1 or end == -1 or end < begin:
        raise SystemExit(f"{path}: generated markers not found or out of order; "
                         "run without --check once to seed them")
    begin_content = begin + len(MARK_BEGIN)
    return text[:begin_content] + span + text[end:]


def whole_generated_file(span):
    return MARK_BEGIN + "\n" + span + MARK_END + "\n"


def read(path):
    if not os.path.exists(path):
        return ""
    with open(path, encoding="utf-8") as f:
        return f.read()


def write(path, content):
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def diff(label, before, after):
    if before == after:
        return []
    return list(difflib.unified_diff(before.splitlines(keepends=True),
                                      after.splitlines(keepends=True),
                                      fromfile=f"{label} (on disk)",
                                      tofile=f"{label} (regenerated)"))


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--check", action="store_true",
                   help="regenerate and diff instead of writing; exit != 0 on drift")
    args = p.parse_args()

    cells = load_cells()
    design_span = render_design_span(cells) + " "
    checklist_content = whole_generated_file(render_checklist(cells))

    design_before = read(DESIGN_MD)
    if MARK_BEGIN not in design_before:
        raise SystemExit(f"{DESIGN_MD}: no {MARK_BEGIN!r} marker found")
    design_after = splice(design_before, design_span, DESIGN_MD)

    checklist_before = read(CHECKLIST_MD)
    checklist_after = checklist_content

    if args.check:
        d1 = diff("DESIGN.md", design_before, design_after)
        d2 = diff("docs/release-checklist.md", checklist_before, checklist_after)
        if not d1 and not d2:
            print("acceptance-manifest: DESIGN.md and docs/release-checklist.md "
                 "agree with tests/acceptance/cells.json")
            return 0
        for d in (d1, d2):
            if d:
                sys.stdout.writelines(d)
        print("\nacceptance-manifest: drift detected; run "
             "tools/acceptance_manifest.py to regenerate", file=sys.stderr)
        return 1

    write(DESIGN_MD, design_after)
    write(CHECKLIST_MD, checklist_after)
    print("acceptance-manifest: regenerated DESIGN.md and docs/release-checklist.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
